USE DML;
--CREATEING TABEL MY_EMPLOYEES
/*CREATE TABLE MY_EMPLOYEES(ID INT, LAST_NAME VARCHAR(25), FIRST_NAME VARCHAR (25), USERID VARCHAR(8), SALARY INT);*/

--iNSERTING DATA IN MY_EMPOLYEE TABLE
/*INSERT INTO MY_EMPLOYEES VALUES (1,'PATEL','RALPH','RPATEL',895),
						       (2,'DANCS','BETTY','BDANCS',860);
							   */
--Confirming the addition 
--SELECT * FROM MY_EMPLOYEES;
GO
/*DECLARE @ID INT, 
@LAST_NAME VARCHAR(25), 
@FIRST_NAME VARCHAR(25), 
@USERID VARCHAR(8),
@SALARY DECIMAL(9,2);

SET @ID = 3;
SET @LAST_NAME = 'SANKAR';
SET @FIRST_NAME = 'KIRAN';
SET @USERID = LEFT(@FIRST_NAME,1) + LEFT(@LAST_NAME,7);
SET @SALARY = 2000;


INSERT INTO MY_EMPLOYEES VALUES(@ID, @LAST_NAME, @FIRST_NAME, @USERID, @SALARY);
SELECT * FROM MY_EMPLOYEES;
GO*/

--UPDATE MY_EMPLOYEES SET LAST_NAME = 'DREXLER' WHERE LAST_NAME = 'SANKAR';
--SELECT * FROM MY_EMPLOYEES;

--UPDATE MY_EMPLOYEES SET SALARY = 1000 WHERE SALARY <=1000;
--SELECT * FROM MY_EMPLOYEES;

--DELETE FROM MY_EMPLOYEES WHERE ID = 2;
--SELECT * FROM MY_EMPLOYEES;

DROP TABLE MY_EMPLOYEES;

