use Practise;
/*Go
CREATE TABLE DEPARTMENTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
GO*/

/*Go
INSERT INTO DEPARTMENTS (ID, NAME) 
VALUES 
(1, 'sales'), (2, 'Design'), (3, 'marketing'),
(4, 'product'), (5, 'sales');
GO
*/

/*CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SALARY INT  NOT NULL,
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID));
GO
*/
GO
/*INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID) 
VALUES 
(11, 'Raj', 'Kumar', 30000, 1),
(12, 'sanjay', 'krishna', 45000, 2),
(13, 'Mohamed', 'Tharic', 28000, 3),
(14, 'Muthu', 'Mani', 50000, 4),
(15, 'sankar', 'Kiran', 90000, 5);
GO */

/*CREATE TABLE TRG_DEPT(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) );
	Go*/

/*INSERT INTO TRG_DEPT (ID,NAME)
SELECT ID, NAME FROM DEPARTMENTS;
GO*/

/*SELECT ID,NAME 
INTO DEPT101
FROM DEPARTMENTS;
GO*/


/*GO
CREATE TABLE TRG_EMP (
    ID INT PRIMARY KEY,
    LAST_NAME VARCHAR(25) NOT NULL,
    FIRST_NAME VARCHAR(25) NOT NULL,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES TRG_DEPT(ID)
);
GO*/

/*
ALTER TABLE TRG_EMP 
ALTER COLUMN LAST_NAME VARCHAR(50);
*/

/*SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID AS DEPT_ID
INTO TRG_EMPLOYEES
FROM EMPLOYEES;*/

/*DROP TABLE TRG_EMP;*/

/*EXEC sp_rename 'dbo.EMPLOYEES' , 'dbo.TRG_EMP'*/
/*GO
ALTER TABLE TRG_EMP
DROP COLUMN FRIST_NAME;
GO*/
GO
SELECT * FROM DEPT101;
SELECT * FROM TRG_EMP;
SELECT * FROM TRG_DEPT;
GO