use Selectcommand;
--CREATING TABLE FOR EMPLOYEE
/*CREATE TABLE EMPLOYEES (ENAME VARCHAR(10), 
                  EMPNO INT NOT NULL,
				  JOB VARCHAR(9),
				  MGR INT,
				  HIREDATE DATE,
				  SAL INT,
				  COMM INT,
				  DEPTNO INT NOT NULL); */
				  
/*INSERT INTO EMPLOYEES (ENAME, EMPNO, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES 
    ('HOMNATH', 419, 'PRESIDENT', 419, '2004-01-09', 100000, 1, 1); */
--SELECT * FROM EMPLOYEES;

--CREATING TABLE DEPARTMENT
/*CREATE TABLE DEPARTMENT (DEPTNO INT NOT NULL,
                         DNAME VARCHAR(14),
						 LOC VARCHAR(13)); */
/*INSERT INTO DEPARTMENT VALUES (10,'MANAGER','CHENNAI'),
                              (20,'ANALYST','MUMBAI'),
							  (1,'PRESIDENT','CANADA'),
							  (5,'HR','BOSTON'),
							  (40,'CLERK','MADURAI'),
							  (50,'SALESMAN','CHENNAI'); */
 
 --1.
 /*SELECT ENAME,JOB, SAL AS SAL
	 FROM EMPLOYEES;*/
--TRUE
--2.
 --SELECT * FROM DEPARTMENT;

 --3.
 /*SELECT EMPNO,ENAME, SAL *12 , 'ANNUAL SALARIES'
 FROM EMPLOYEES;*/ -- CORRECTED SYNTAX
 --4.
 --SELECT*FROM DEPARTMENT;

 --5.
 --EXEC sp_help 'EMPLOYEES'; -- THIS SHOWS THE STRUCTURE OF EMPLOYEE TABLE
 /*SELECT ENAME AS EMPLOYEENAME,
        EMPNO,
		JOB,
		MGR,
		HIREDATE AS STARTDATE,
		SAL,
		COMM,
		DEPTNO
FROM EMPLOYEES; */

--6.
/*SELECT DISTINCT JOB
FROM EMPLOYEES; */

--7.
/*
SELECT ENAME AS EMPLOYEES,
       EMPNO AS EMP#,
	   JOB AS JOBTITLE,
	   MGR,
	   HIREDATE,
	   SAL,
	   COMM,
	   DEPTNO
FROM EMPLOYEES;*/
     

