use Task;
--TASK 1:
--CREATE TABLE STUDENTS (STUD_ID INT , SECTION VARCHAR (5), AGE INT CHECK(AGE>=19));
--EXEC sp_helpconstraint STUDENTS;

--TASK 2:
--CREATE TABLE PRODUCTS (PROD_ID INT NOT NULL, PROD_NAME VARCHAR(20) NOT NULL);
/*INSERT INTO PRODUCTS VALUES(12,'HARD DISK'),
                           (12,'SSD');
						   */
--SELECT * FROM PRODUCTS;
/*UPDATE TOP(1) PRODUCTS 
SET PROD_ID = 11
WHERE PROD_ID = 12;*/
--SELECT * FROM PRODUCTS;



--TASK 3:
--CREATE TABLE CUSTOMER(CUST_ID INT , CUST_NAME VARCHAR(20));
--ALTER TABLE CUSTOMER ADD CONSTRAINT CHECK_CUSTOMER CHECK (CUST_ID >= 10);
/*INSERT INTO CUSTOMER VALUES (11,'SAM'),
						    (10,'SANJAY'),
						    (12,'KRISHNA');
							*/
--SELECT * FROM CUSTOMER;